services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    entrypoint: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
       condition: service_healthy

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s


volumes:
  mysql_volume:
  static_volume:
  media_volume:
